### ISSUE TITLE
Replace SqPaymentForm by Web Payments SDK 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/square-plugin-for-nopcommerce#4]
> We wanted to remind you that the SqPaymentForm JavaScript library will be retired on 2022/07/21 and its functionality will be shut off. SqPaymentForm has been replaced by the Web Payments SDK and we encourage you to migrate as soon as possible by following this step-by-step migration guide.

Source: https://www.nopcommerce.com/boards/topic/93697/square-is-retiring-sqpaymentform

**Comment by skoshelev** [comment]
Closed by https://github.com/nopSolutions/square-plugin-for-nopcommerce/commit/2cec72a2d303f01bb0694c6a03eaa7221bac49a4
